name: Perf different solvers on Sierpinski

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TIMEOUT: 10s
  OPAMROOT: /home/user/.opam

jobs:
  sierpinski:
    runs-on: ubuntu-latest
    container:
      image: we1ine/chrobelias:latest
      options: --user root --init
    strategy:
      fail-fast: false
      matrix:
        solver:
          - "bin/chro.exe"
          - "bin/swine"
    steps:
      - run: opam --version
      - run: opam exec -- ocamlopt --version

      - uses: actions/checkout@v4
        with:
          submodules: true

      # Disabled since the docker image is used.

      #- uses: ocaml/setup-ocaml@v3
      #  with:
      #    ocaml-compiler: 5.3
      #    dune-cache: true

      #- name: Install Smtml depedencies
      #  working-directory: ./vendor/smtml
      #  run: opam install . --deps-only --with-test --with-dev-setup

      #- name: Install depedencies
      #  run: opam install . --deps-only --with-test

      - name: List opam packages
        run: opam list

      - name: Build
        run: opam exec -- dune build @all

      - name: Run ${{ matrix.solver }} on sierpinski benchmarks
        run: |
          ./.github/workflows/run-benchmarks.sh "${{ matrix.solver }}" benchmarks/chrobelias/QF_EIA/SIERPINSKI $TIMEOUT

      - name: Get stats
        run: |
          ./.github/workflows/stat-benchmarks.sh "${{ matrix.solver }}" benchmarks/chrobelias/QF_EIA/SIERPINSKI
