name: Perf different solvers on StrRElnc

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TIMEOUT: 10s
  OPAMROOT: /home/user/.opam

jobs:
  strrelnc-solvers:
    runs-on: ubuntu-latest
    container:
      image: we1ine/chrobelias:latest
      options: --user root --init
    strategy:
      fail-fast: false
      matrix:
        solver:
          - "bin/chro.exe"
          - "bin/chro.exe -under-all -sbcnt 10 -sblen 5"
          - "bin/ostrich2"
          - "bin/cvc5"
          - "bin/z3-noodler"
          - "bin/z3"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Disabled since the docker image is used.

      #- uses: ocaml/setup-ocaml@v3
      #  with:
      #    ocaml-compiler: 5.3
      #    dune-cache: true

      #- name: Install Smtml depedencies
      #  working-directory: ./vendor/smtml
      #  run: opam install . --deps-only --with-test --with-dev-setup

      #- name: Install depedencies
      #  run: opam install . --deps-only --with-test

      - name: List opam packages
        run: opam list

      - name: Build
        run: opam exec -- dune build @all

      - name: Run ${{ matrix.solver }} on strrelnc benchmarks
        run: |
          ./.github/workflows/run-benchmarks.sh "${{ matrix.solver }}" ./benchmarks/chrobelias/QF_SLIA/StrRElnc/RElnc $TIMEOUT

      - name: Get stats
        run: |
          ./.github/workflows/stat-benchmarks.sh "${{ matrix.solver }}" ./benchmarks/chrobelias/QF_SLIA/StrRElnc/RElnc
